remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme

title: WhatDataset?
theme: jekyll-theme-cayman

description: The Right Data for the Right Questions

show_downloads: false
baseurl: "/whatdataset.github.io"
google_analytics:

collections:
  datasets:
    output: true